import type { MenuCategory, MenuItem } from "./types";

export const menuCategories: MenuCategory[] = [
  { id: "cat-entradas",  name: "Entradas",   position: 1 },
  { id: "cat-principales", name: "Principales", position: 2 },
  { id: "cat-parrilla",  name: "Parrilla",    position: 3 },
  { id: "cat-bebidas",   name: "Bebidas",     position: 4 },
  { id: "cat-postres",   name: "Postres",     position: 5 },
];

export const menuItems: MenuItem[] = [
  // ── Entradas ────────────────────────────────────────────────────────────────
  {
    id: "item-ent-1",
    restaurant_id: "rest-bistro",
    category_id: "cat-entradas",
    name: "Burrata con tomates confitados",
    description: "Burrata cremosa sobre cama de tomates confitados al horno lento, aceite de albahaca y flor de sal. Suave, untuosa y llena de sabor.",
    price: 22,
    station: "cold",
    available: true,
    featured: true,
    image_url: "/bistro-ent-burrata.jpg",
  },
  {
    id: "item-ent-2",
    restaurant_id: "rest-bistro",
    category_id: "cat-entradas",
    name: "Croquetas de osobuco braseado",
    description: "Croquetas crujientes por fuera con corazón de osobuco braseado al vino tinto. Servidas con aioli de limón.",
    price: 19,
    station: "hot",
    available: true,
    featured: false,
    image_url: "/bistro-ent-croquetas.jpg",
  },
  {
    id: "item-ent-3",
    restaurant_id: "rest-bistro",
    category_id: "cat-entradas",
    name: "Provoleta ahumada con chutney de tomate",
    description: "Provoleta fundida en plancha con ahumado suave, acompañada de chutney casero de tomate y orégano fresco.",
    price: 17,
    station: "grill",
    available: true,
    featured: false,
    image_url: "/bistro-ent-provoleta.jpg",
  },

  // ── Principales ─────────────────────────────────────────────────────────────
  {
    id: "item-pri-1",
    restaurant_id: "rest-bistro",
    category_id: "cat-principales",
    name: "Risotto de hongos patagónicos",
    description: "Hongos patagónicos salteados a fuego vivo, fundidos en arroz cremoso con parmesano añejo y aceite de trufa. Reconfortante y elegante.",
    price: 26,
    station: "hot",
    available: true,
    featured: true,
    image_url: "/bistro-pri-risotto.jpg",
  },
  {
    id: "item-pri-2",
    restaurant_id: "rest-bistro",
    category_id: "cat-principales",
    name: "Ravioles de calabaza y salvia",
    description: "Pasta fresca rellena de puré de calabaza asada, manteca clarificada con salvia y parmesano rallado en el momento.",
    price: 24,
    station: "hot",
    available: true,
    featured: false,
    image_url: "/bistro-pri-ravioles.jpg",
  },
  {
    id: "item-pri-3",
    restaurant_id: "rest-bistro",
    category_id: "cat-principales",
    name: "Salmón grillado con puré de coliflor",
    description: "Salmón del Atlántico grillado al punto, sobre puré aterciopelado de coliflor con manteca tostada y alcaparras fritas.",
    price: 32,
    station: "grill",
    available: true,
    featured: false,
    image_url: "/bistro-pri-salmon.jpg",
  },

  // ── Parrilla ────────────────────────────────────────────────────────────────
  {
    id: "item-par-1",
    restaurant_id: "rest-bistro",
    category_id: "cat-parrilla",
    name: "Ojo de bife con papas rotas",
    description: "Ojo de bife madurado 21 días a la brasa, con papas rotas doradas en aceite de oliva y romero. La estrella de nuestra parrilla.",
    price: 42,
    station: "grill",
    available: true,
    featured: true,
    image_url: "/bistro-par-ojo-de-bife.jpg",
  },
  {
    id: "item-par-2",
    restaurant_id: "rest-bistro",
    category_id: "cat-parrilla",
    name: "Entraña marinada con chimichurri cítrico",
    description: "Entraña tierna marinada 12 horas en hierbas y ajo, servida con nuestro chimichurri cítrico de limón y naranja.",
    price: 34,
    station: "grill",
    available: true,
    featured: false,
    image_url: "/bistro-par-entrana.jpg",
  },
  {
    id: "item-par-3",
    restaurant_id: "rest-bistro",
    category_id: "cat-parrilla",
    name: "Pollo de campo al limón",
    description: "Pollo de campo partido a la mitad, marinado en limón y hierbas, cocido a las brasas. Jugoso, aromático y sin complicaciones.",
    price: 28,
    station: "grill",
    available: true,
    featured: false,
    image_url: "/bistro-par-pollo.jpg",
  },

  // ── Bebidas ─────────────────────────────────────────────────────────────────
  {
    id: "item-beb-1",
    restaurant_id: "rest-bistro",
    category_id: "cat-bebidas",
    name: "Limonada de menta y jengibre",
    description: "Limonada natural con hojas de menta fresca y jengibre rallado. Refrescante y sin alcohol.",
    price: 8,
    station: "bar",
    available: true,
    featured: false,
    image_url: "/bistro-beb-limonada.jpg",
  },
  {
    id: "item-beb-2",
    restaurant_id: "rest-bistro",
    category_id: "cat-bebidas",
    name: "Agua con gas",
    description: "Agua mineral con gas, botella 500ml.",
    price: 4,
    station: "bar",
    available: true,
    featured: false,
    image_url: "/bistro-beb-agua-gas.jpg",
  },
  {
    id: "item-beb-5",
    restaurant_id: "rest-bistro",
    category_id: "cat-bebidas",
    name: "Coca-Cola",
    description: "Coca-Cola clásica bien fría, lata 354ml.",
    price: 5,
    station: "bar",
    available: true,
    featured: false,
    image_url: "/bistro-beb-coca-cola.jpg",
  },
  {
    id: "item-beb-3",
    restaurant_id: "rest-bistro",
    category_id: "cat-bebidas",
    name: "Espresso",
    description: "Café espresso de origen único, extracción doble.",
    price: 5,
    station: "bar",
    available: true,
    featured: false,
    image_url: "/bistro-beb-espresso.jpg",
  },
  {
    id: "item-beb-6",
    restaurant_id: "rest-bistro",
    category_id: "cat-bebidas",
    name: "Café con leche",
    description: "Espresso con leche vaporizada al punto. También disponible en versión descafeinada.",
    price: 6,
    station: "bar",
    available: true,
    featured: false,
    image_url: "/bistro-beb-cafe-con-leche.jpg",
  },
  {
    id: "item-beb-4",
    restaurant_id: "rest-bistro",
    category_id: "cat-bebidas",
    name: "Mocktail de frutos rojos",
    description: "Combinación de frutos rojos, jugo de maracuyá, jengibre y soda. Festivo, frutal y sin alcohol.",
    price: 10,
    station: "bar",
    available: true,
    featured: false,
    image_url: "/bistro-beb-mocktail.jpg",
  },

  // ── Postres ─────────────────────────────────────────────────────────────────
  {
    id: "item-pos-1",
    restaurant_id: "rest-bistro",
    category_id: "cat-postres",
    name: "Tiramisú de la casa",
    description: "Tiramisú clásico en versión personal: café fuerte, mascarpone esponjoso y cacao amargo. Receta de siempre, ejecución impecable.",
    price: 14,
    station: "cold",
    available: true,
    featured: true,
    image_url: "/bistro-pos-tiramisu.jpg",
  },
  {
    id: "item-pos-2",
    restaurant_id: "rest-bistro",
    category_id: "cat-postres",
    name: "Flan cremoso con dulce de leche",
    description: "Flan casero de vainilla con caramelo oscuro y un generoso copete de dulce de leche artesanal.",
    price: 12,
    station: "cold",
    available: true,
    featured: false,
    image_url: "/bistro-pos-flan.jpg",
  },
  {
    id: "item-pos-3",
    restaurant_id: "rest-bistro",
    category_id: "cat-postres",
    name: "Panna cotta de vainilla",
    description: "Panna cotta suave con vainilla de Madagascar, coulis de frutos rojos y flores comestibles.",
    price: 13,
    station: "cold",
    available: true,
    featured: false,
    image_url: "/bistro-pos-pannacotta.jpg",
  },
];
